[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "github.com/Eneco/landscaper"
    non-go = false
    unused-packages = false

  [[prune.project]]
    name = "github.com/otaviof/vault-handler"
    non-go = false
    unused-packages = false

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/buildkite/interpolate"

[[constraint]]
  name = "github.com/otaviof/vault-handler"
  version = "0.2.1"

[[constraint]]
  name = "github.com/Eneco/landscaper"
  version = "v1.0.21"

[[override]]
  name = "k8s.io/helm"
  version = "2.11.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.11.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[override]]
  name = "github.com/golang/protobuf"
  version = "=1.1.0"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "9be88ef10da45f8260fac1eafa747a2898949f51"

[[override]]
  name = "k8s.io/utils"
  revision = "011bbbe3b2878d9b1d484312f186826acd7e78cc"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.1"

[[override]]
  name = "github.com/docker/go-connections"
  version = "v0.3.0"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/docker/docker"
  revision  = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

[[override]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.0"